site_name: EPITA - Documentation
theme: readthedocs
repo_url: https://github.com/epita/epita-doc/
pages:
  - Home: 'index.md'
  - Documentation:
    - PIE: 'pie.md'
    - 'git.md'
    - 'wifi.md'
    - Netboot : 'archlinux_netboot.md'
    - AFS: 'afs.md'
    - 'map.md'
    - 'news.md'
  - Accounts:
    - Cri and Bocal accounts: 'accounts.md'
    - Recover and modify passwords: 'passwords.md'
  - Contact:  'contact.md'
